version: "3.9" # optional since v1.27.0
services:
  hubs:
    build:
        context: ./
    ports:
      - "3333:3333"
    environment:
      APP_PORT: 3333
      MONGODB_PATH: mongodb://mongo:27017/hubsdb 
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SCHEDULER_INTERVAL: 45 * * * * *
      DELAY_MILLISECONDS_TASKS: 10 * 60 * 1000
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo"

