version: "3.9" # optional since v1.27.0
services:
    hubs:
        build:
            context: ./
        ports:
            - "3333:3333"
        environment:
            APP_PORT: 3333
            MONGODB_PATH: mongodb://mongo:27017/hubsdb
            REDIS_HOST: redis
            REDIS_PORT: 6379
            SCHEDULER_INTERVAL: 45 * * * * *
            DELAY_MILLISECONDS_TASKS: 10 * 60 * 1000
        links:
            - mongo
            - redis
        depends_on:
            - mongo
            - redis
    redis:
        image: redis
        ports:
            - "6379:6379"
    mongo:
        container_name: container-mongodb
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017

        environment:
            MONGO_INITDB_DATABASE: hubsdb
    
        volumes:
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro   
            - /opt/h2-data
    frontendhubs:
        build:
            context: ../frontendhubs/CardsInfra/
            args:
                REACT_APP_GETHUBS_URL: http://localhost:3333/hubs
                REACT_APP_REGISTERHUB_URL: http://localhost:3333/hubsapis/
                REACT_APP_GERARCSV: http://localhost:3333/logs
                REACT_APP_BAIXARCSV: http://localhost:3333/logs
        ports:
            - "80:80"
        
        